include!("sports_parts/academic_earth.rs");
include!("sports_parts/premiership_rugby.rs");
include!("sports_parts/matchitv.rs");
include!("sports_parts/sztv.rs");
include!("sports_parts/arnes.rs");
include!("sports_parts/cjsw.rs");
include!("sports_parts/daystar.rs");
include!("sports_parts/dctp.rs");
include!("sports_parts/ettu_tv.rs");
