use super::*;

include!("tests_parts/registry.rs");
include!("tests_parts/native_a.rs");
include!("tests_parts/native_b.rs");
include!("tests_parts/native_c.rs");
include!("tests_parts/native_d.rs");
include!("tests_parts/native_e.rs");
include!("tests_parts/native_f.rs");
include!("tests_parts/native_g.rs");
include!("tests_parts/native_h.rs");
include!("tests_parts/ninegag.rs");
include!("tests_parts/myvidster.rs");
include!("tests_parts/glide.rs");
include!("tests_parts/ebay.rs");
include!("tests_parts/sen.rs");
include!("tests_parts/roya.rs");
include!("tests_parts/reverbnation.rs");
include!("tests_parts/ettu_tv.rs");
include!("tests_parts/elonet.rs");
include!("tests_parts/golem.rs");
include!("tests_parts/screen9.rs");
include!("tests_parts/bild.rs");
include!("tests_parts/filmarchiv.rs");
include!("tests_parts/fathom.rs");
